import { readdirSync, readFileSync, writeFileSync, statSync, mkdirSync } from 'node:fs'
import { join, basename, dirname } from 'node:path'

// 构建期生成器：扫描 prompts/**/*.md → 生成 bundled 的 TS 注册表。
// md 是可编辑源（对齐交付文档 8.2）；生成的 .ts 被正常 import/打包，零运行时 fs、零 standalone 部署风险。
// 文件名（去 .md）即 prompt key。改 md 后由 predev/prebuild 自动重新生成。

const ROOT = process.cwd()
const PROMPTS_DIR = join(ROOT, 'prompts')
const OUT = join(ROOT, 'src/lib/server/prompts/registry.generated.ts')

function walk(dir) {
  const out = []
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) out.push(...walk(p))
    else if (name.endsWith('.md')) out.push(p)
  }
  return out
}

const entries = {}
for (const f of walk(PROMPTS_DIR)) {
  const key = basename(f, '.md')
  if (key === 'SOURCE_LIBRARY') continue // 源文档索引，不编入 runtime registry
  if (entries[key]) throw new Error(`[build-prompts] 重复 prompt key: ${key}（${f}）`)
  entries[key] = readFileSync(f, 'utf8').replace(/\s+$/, '') // 去尾部空白，内部原样保留
}

const keys = Object.keys(entries).sort()
const body = keys.map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(entries[k])},`).join('\n')
const content = `// AUTO-GENERATED by scripts/build-prompts.mjs — 请勿手改。\n// 编辑 prompts/**/*.md 后运行 npm run dev / npm run build 会自动重新生成。\nexport const promptRegistry = {\n${body}\n} as const\n`

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, content)
console.log(`[build-prompts] 生成 ${keys.length} 个 prompt → src/lib/server/prompts/registry.generated.ts`)
